## Basic configuration
style_image: img/icy.jpg
naming: 'icy'
model_path: style_models


## Weight of the loss
content_weight: 1.0         # weight for content features loss
style_weight: 100.0         # weight for style features loss
tv_weight: 0.0              # weight for total variation loss


## The size, the iter number to run
train_data_path: /home/xu/store/deep/style/train2014
format: jpg
image_size: 256
batch_size: 4
epoch: 4


## Loss Network
loss_model: 'vgg_16'
content_layers:             # use these layers for content loss
  - 'vgg_16/conv3/conv3_3'
style_layers:               # use these layers for style loss
  - "vgg_16/conv1/conv1_2"
  - "vgg_16/conv2/conv2_2"
  - "vgg_16/conv3/conv3_3"
  - "vgg_16/conv4/conv4_3"
checkpoint_exclude_scopes: 'vgg_16/fc'      # we only use the conv layer
loss_model_file: 'pre_vgg_ckpt/vgg_16.ckpt'
